title:              L'idéomètre
email:              contact@ideometre.com
description:        Des idées grandes comme ça!
author:             MX
baseurl:            ""
url:                "https://www.ideometre.com"

# Social Profiles
twitter_username:   ideometre
github_username:    ideometre
facebook_username:  
instagram_username:  ideometre
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag